---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: bosh-cpi-src-in

run:
  path: bosh-cpi-src-in/ci/tasks/cleanup-leftover-environments.sh

params:
  BBL_AWS_ACCESS_KEY_ID: ""
  BBL_AWS_SECRET_ACCESS_KEY: ""
  BBL_AWS_REGION: us-west-1
