---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}
inputs:
  - name: bosh-cpi-src
  - name: environment
run:
  path: bosh-cpi-src/ci/tasks/ensure-terminated.sh
params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION:    ""
