---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}
inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-release
  - name: release-version-semver
  - name: bosh-cli
outputs:
  - name: promoted
  - name: release-metadata
run:
  path: bosh-cpi-src/ci/tasks/promote-candidate.sh
params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ASSUME_ROLE_ARN:   ""
