---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: bosh-aws-cpi-release

run:
  path: bosh-aws-cpi-release/ci/tasks/run-unit-specs.sh
