---
platform: linux

image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: bosh-aws-cpi-release
  - name: environment
  - name: stemcell
  - name: heavy-stemcell
  - name: director-state

run:
  path: bosh-aws-cpi-release/ci/tasks/run-e2e.sh

params:
  BOSH_DEBUG_LEVEL:     info
  BOSH_AWS_KMS_KEY_ARN: ""
